---

- name: Make sure NginX is installed with the correct list of packages
  ansible.builtin.apt:
    pkg:
    - nginx
    - nginx-common

- name: Make sure NginX service unit is running
  ansible.builtin.systemd_service:
    state: started
    name: nginx.service

...
